export const SYSTEM_PROMPT_TRANSLATE_ENGLISH = "You are a translation bot. If the text sent is in English, just parrot the text sent back without doing anything, and if it is in a language other than English, translate it into English and send it back. Return only the translated text."
export const SYSTEM_PROMPT_GENERATE_IMAGE_RANDOM = "Create a prompt to send to the image generation AI in English. Do not include your instruction and conclusion in your return.  Return only the description or characteristics of the generated image."
export const USER_PROMPT_RANDOM = "Create a prompt to pass to the image generation AI about \"{TOPIC}\". Return prompt that include a variety of factors, such as race, gender, generation (age), number of people, landscape, space, emotion, animal, city, place, nature, or scene. However, it is not necessary to include all elements."
export const MAGIC_PROMPT_TOPICS = [
	"Space",
	"Traveling",
	"Camping",
	"Cooking",
	"Investing",
	"Programming",
	"Driving cars",
	"Playing football (soccer)",
	"Playing baseball",
	"Playing basketball",
	"Playing tennis",
	"Playing volleyball",
	"Interior design",
	"Furniture",
	"Blogging",
	"Reading books",
	"Dancing",
	"Singing",
	"Listening to music",
	"Playing musical instruments (piano, guitar etc.)",
	"Learning new languages",
	"Shopping",
	"Hiking",
	"Cycling",
	"Exercising",
	"Drawing",
	"Painting",
	"Playing computer games",
	"Baking",
	"Gardening",
	"Doing crafts (handmade)",
	"Embroidering",
	"Playing board games",
	"Walking",
	"Writing stories",
	"Fishing",
	"Photography",
	"Skydiving",
	"Skating",
	"Skiing",
	"Snowboarding",
	"Longboarding",
	"Surfing",
	"Yoga",
	"Designing clothing",
	"Graphic design",
	"Web design",
	"Making Lego sets",
	"Bonsai",
	"Makeup",
	"Car racing",
	"Home Improvement Ideas",
	"Scuba diving",
	"Golfing",
	"Gymnastics",
	"Martial arts",
	"Rock climbing"
]