export const languageMap = {
	'de_DE': 'German',
	'en_US': 'English',
	'es_ES': 'Spanish',
	'fr_FR': 'French',
	'it_IT': 'Italian',
	'ja_JP': 'Japanese',
	'ko_KR': 'Korean',
	'nl_NL': 'Dutch',
	'nn_NO': 'Norwegian',
	'pl_PL': 'Polish',
	'pt_BR': 'Brazilian Portuguese',
	'pt_PT': 'Portuguese',
	'sv_SE': 'Swedish',
	'zh_CN': 'Chinese (Simplified)',
	'zh_TW': 'Chinese (Traditional)',
}
export const languageMapForTranscription = {
	'de': 'German',
	'en': 'English',
	'es': 'Spanish',
	'fr': 'French',
	'it': 'Italian',
	'ja': 'Japanese',
	'ko': 'Korean',
	'nl': 'Dutch',
	'no': 'Norwegian',
	'pl': 'Polish',
	'pt': 'Portuguese',
	'sv': 'Swedish',
	'zh': 'Chinese',
}